#!/usr/bin/python3

# Copyright (c) 2020 AT&T Intellectual Property.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

import argparse

from vyatta import tacplus
from vyatta.tacplus import utils

RPCS = {}

def main():
    parser = argparse.ArgumentParser(description="TACACS+ RPCs")
    parser.add_argument("RPC", action="store", choices=RPCS.keys(), help="RPC name")
    args = parser.parse_args()

    try:
        return RPCS[args.RPC]()
    except tacplus.DaemonNotRunning as e:
        utils.print_err(e)
    except Exception as e:
        utils.print_err(f"An unexpected error occurred during RPC '{args.RPC}': {e}")
    return -1

if __name__ == "__main__":
    exit(main())
